### ISSUE TITLE
请问页面间如何跳转？按微信文档上写报错,试了多种方式都报错

### ISSUE THREAD

**Issue by huf307012** [uileader/touchui#1]
![image](https://user-images.githubusercontent.com/25561599/40033946-43001678-582d-11e8-8f80-9e99a31263bf.png)
![image](https://user-images.githubusercontent.com/25561599/40033948-4e993500-582d-11e8-846b-9afc297a717b.png)
不加后缀无法进入wx.navigateTo()方法

**Comment by huf307012** [comment]
touchuiwx

**Comment by uileader** [comment]
已修复路径问题
