### ISSUE TITLE
这个怎么解决

### ISSUE THREAD

**Issue by QTTQ** [uileader/touchui#15]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by QTTQ** [comment]
<script>
var Bus = require("#/static/utils/onfire");
export default {
  methods: {
    navHandle() {
      Bus.fire("fireAction", 111);
    }
  }
};
</script>

结果触发事件却显示Bus.fire不是个方法。
Uncaught TypeError: Bus.fire is not a function

**Comment by pangxiaodun** [comment]
`mounted () {
    var script = document.createElement("script")
    script.type = "text/javascript"
    script.src="https://cdn.bootcss.com/onfire.js/1.0.6/onfire.js"
    document.body.appendChild(script)

    script.onload = function(){
        console.log(onfire,'1111111342ef')
        function test_callback(data1, data2) {
          console.log('this is a event 1');
        }

        // 绑定事件
        var eventObj = onfire.on('test_event', test_callback);
        var eventObj2 = onfire.on('test_event', function(data1, data2) {
          console.log('this is a event 2');
        });

        // 触发事件
        onfire.fire('test_event', 'test_data1', 'test_data2');

        // 取消绑定
        onfire.un(eventObj); // 取消绑定这个事件.
        onfire.un('test_event'); // 取消绑定所有的 `test_event`.
        onfire.un(test_callback); // 取消绑定所有的 `test_callback` 方法.
    }
  }`

**Comment by QTTQ** [comment]
哦哦  谢谢
