### ISSUE TITLE
VS 安装后项目启动报错

### ISSUE THREAD

**Issue by 872601188** [uileader/touchui#16]
请教大家，安装VS与相关插件后 ，启动 TouchUI 项目报错

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2255 
扩展宿主意外终止。
e.onDidNotificationChange @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2255

不知道需要如何处理

**Comment by uileader** [comment]
可以加入交流群交流此问题
