### ISSUE TITLE
感觉吧

### ISSUE THREAD

**Issue by owen-carter** [uileader/touchui#19]
1，创建方式很奇怪，为什么只支持，vscode？不支持 cli init 的方式？
2，ui文件后缀，这个是vue做的，那就vue就行了吧？搞这个有什么意义？
3，npm script 不好用么？非要这么标新立异么？

**Comment by erguotou520** [comment]
同感

**Comment by XinJiangQingMang** [comment]
如果采用一楼的方式这个项目早就火了。搞不懂这个项目的目的 还花这么大功夫  如果我用你的播放器 想扩展播m3u8我都只能定制? 这就是达到目的了
