### ISSUE TITLE
ui-table 动态数据示例设置固定列后引起的问题

### ISSUE THREAD

**Issue by tears008** [uileader/touchui#2]
修改文件：touchui/pages/componentDemo/table3.ui 中的第一列为固定列之后：
`{
        name: 'id',
        display: '编号',
        sort: true,
        width: '64',
        align: 'center',
        headerAlign: 'center',
        fixed : 'left'
      }
`
编号这一列会显示两次，并且会无限请求设置的Url。

**Comment by uileader** [comment]
新版本已修复
